<Project Sdk="Microsoft.NET.Sdk.Web">

	<PropertyGroup>
		<TargetFramework>net10.0</TargetFramework>
		<Nullable>enable</Nullable>
		<ImplicitUsings>enable</ImplicitUsings>
		<UserSecretsId>6243fd72-5da4-4a04-8436-b26f20060b09</UserSecretsId>
		<DockerDefaultTargetOS>Linux</DockerDefaultTargetOS>
	</PropertyGroup>

	<ItemGroup>
		<PackageReference Include="Google.Protobuf" Version="3.35.1" />
		<PackageReference Include="Grpc.Net.Client" Version="2.80.0" />
		<PackageReference Include="Grpc.Net.ClientFactory" Version="2.80.0" />
		<PackageReference Include="Grpc.Tools" Version="2.81.1">
		  <PrivateAssets>all</PrivateAssets>
		  <IncludeAssets>runtime; build; native; contentfiles; analyzers; buildtransitive</IncludeAssets>
		</PackageReference>
		<PackageReference Include="HotChocolate.AspNetCore" Version="16.2.0" />
		<PackageReference Include="Mapster" Version="10.0.8" />
		<PackageReference Include="Microsoft.AspNetCore.OpenApi" Version="10.0.9" />
		<PackageReference Include="Microsoft.VisualStudio.Azure.Containers.Tools.Targets" Version="1.23.0" />
	</ItemGroup>

	<ItemGroup>
		<Protobuf Include="Protos\models.proto" GrpcServices="none" />
		<Protobuf Include="Protos\account.proto" GrpcServices="Client" />
		<Protobuf Include="Protos\badge.proto" GrpcServices="Client" />
		<Protobuf Include="Protos\contribution.proto" GrpcServices="Client" />
		<Protobuf Include="Protos\favorite.proto" GrpcServices="Client" />
		<Protobuf Include="Protos\notification.proto" GrpcServices="Client" />
	</ItemGroup>

	<ItemGroup>
		<Folder Include="Extensions\" />
	</ItemGroup>

</Project>
